### ISSUE TITLE
Replace Gentoo Live ISO with standard installer

### ISSUE THREAD

**Issue by nodiscc** [nodiscc/distrib-dl#3]
The Gentoo Live ISO is unmaintained and unnecessary

https://old.reddit.com/r/Gentoo/comments/dud6cj/last_update_to_hybrid_iso_livedvd_in_20160704/

/cc @unixbhaskar

**Comment by unixbhaskar** [comment]
Pick your needs from here :

[https://www.gentoo.org/downloads/](url
